name: Build mythicos-upgrade-info

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Debian build tools
        run: |
          sudo apt update
          sudo apt install -y \
            devscripts \
            debhelper \
            fakeroot \
            build-essential

      - name: Prepare source directory
        run: |
          mkdir src
          shopt -s extglob
          cp -r !(src) src/

      - name: Build package
        run: |
          cd src
          dpkg-buildpackage -us -uc

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mythicos-upgrade-info-build
          path: |
            ${{ github.workspace }}/*.deb
            ${{ github.workspace }}/*.changes
            ${{ github.workspace }}/*.buildinfo
            ${{ github.workspace }}/*.dsc
            ${{ github.workspace }}/*.tar.*
